namespace Kadrovska_sluzba
{
    partial class ucRadnik
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DevExpress.Utils.ContextButton contextButton1 = new DevExpress.Utils.ContextButton();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucRadnik));
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.txtJMBG = new DevExpress.XtraEditors.TextEdit();
            this.mainRibbonControl = new DevExpress.XtraBars.Ribbon.RibbonControl();
            this.bbiSave = new DevExpress.XtraBars.BarButtonItem();
            this.bbiSaveAndClose = new DevExpress.XtraBars.BarButtonItem();
            this.bbiSaveAndNew = new DevExpress.XtraBars.BarButtonItem();
            this.bbiReset = new DevExpress.XtraBars.BarButtonItem();
            this.bbiDelete = new DevExpress.XtraBars.BarButtonItem();
            this.bbiClose = new DevExpress.XtraBars.BarButtonItem();
            this.barEditItem1 = new DevExpress.XtraBars.BarEditItem();
            this.repositoryItemLookUpEdit1 = new DevExpress.XtraEditors.Repository.RepositoryItemLookUpEdit();
            this.mainRibbonPage = new DevExpress.XtraBars.Ribbon.RibbonPage();
            this.mainRibbonPageGroup = new DevExpress.XtraBars.Ribbon.RibbonPageGroup();
            this.xtraTabControl1 = new DevExpress.XtraTab.XtraTabControl();
            this.xtraTabPage1 = new DevExpress.XtraTab.XtraTabPage();
            this.xtraTabPage2 = new DevExpress.XtraTab.XtraTabPage();
            this.memoEdit1 = new DevExpress.XtraEditors.MemoEdit();
            this.pictureEdit1 = new DevExpress.XtraEditors.PictureEdit();
            this.txtPrezime = new DevExpress.XtraEditors.TextEdit();
            this.txtIme = new DevExpress.XtraEditors.TextEdit();
            this.txtDjevPrezime = new DevExpress.XtraEditors.TextEdit();
            this.txtImeOca = new DevExpress.XtraEditors.TextEdit();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForRoot = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForPhoto = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.autoGroupForFirstAndLastName = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForTabs = new DevExpress.XtraLayout.TabbedControlGroup();
            this.autoGroupForContact = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForBDateAndGender = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForHomeAddressAndPhone = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForJob = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForHDateAndSalary = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForEmailAndSkype = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForGroupAndTitle = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlGroup2 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem4 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem5 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem6 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem8 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem7 = new DevExpress.XtraLayout.LayoutControlItem();
            this.txtID = new DevExpress.XtraEditors.TextEdit();
            this.layoutControlItem9 = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtJMBG.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.mainRibbonControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemLookUpEdit1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.xtraTabControl1)).BeginInit();
            this.xtraTabControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.memoEdit1.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureEdit1.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtPrezime.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtIme.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtDjevPrezime.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtImeOca.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForRoot)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForPhoto)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForFirstAndLastName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForTabs)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForContact)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForBDateAndGender)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForHomeAddressAndPhone)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForJob)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForHDateAndSalary)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForEmailAndSkype)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForGroupAndTitle)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtID.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            this.dataLayoutControl1.AllowCustomization = false;
            this.dataLayoutControl1.Controls.Add(this.txtID);
            this.dataLayoutControl1.Controls.Add(this.txtJMBG);
            this.dataLayoutControl1.Controls.Add(this.xtraTabControl1);
            this.dataLayoutControl1.Controls.Add(this.memoEdit1);
            this.dataLayoutControl1.Controls.Add(this.pictureEdit1);
            this.dataLayoutControl1.Controls.Add(this.txtPrezime);
            this.dataLayoutControl1.Controls.Add(this.txtIme);
            this.dataLayoutControl1.Controls.Add(this.txtDjevPrezime);
            this.dataLayoutControl1.Controls.Add(this.txtImeOca);
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 116);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(1027, 321, 450, 400);
            this.dataLayoutControl1.Root = this.layoutControlGroup1;
            this.dataLayoutControl1.Size = new System.Drawing.Size(1073, 702);
            this.dataLayoutControl1.TabIndex = 0;
            // 
            // txtJMBG
            // 
            this.txtJMBG.Location = new System.Drawing.Point(539, 12);
            this.txtJMBG.MenuManager = this.mainRibbonControl;
            this.txtJMBG.Name = "txtJMBG";
            this.txtJMBG.Size = new System.Drawing.Size(522, 20);
            this.txtJMBG.StyleController = this.dataLayoutControl1;
            this.txtJMBG.TabIndex = 11;
            // 
            // mainRibbonControl
            // 
            this.mainRibbonControl.ExpandCollapseItem.Id = 0;
            this.mainRibbonControl.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.mainRibbonControl.ExpandCollapseItem,
            this.bbiSave,
            this.bbiSaveAndClose,
            this.bbiSaveAndNew,
            this.bbiReset,
            this.bbiDelete,
            this.bbiClose,
            this.barEditItem1});
            this.mainRibbonControl.Location = new System.Drawing.Point(0, 0);
            this.mainRibbonControl.MaxItemId = 11;
            this.mainRibbonControl.Name = "mainRibbonControl";
            this.mainRibbonControl.Pages.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPage[] {
            this.mainRibbonPage});
            this.mainRibbonControl.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.repositoryItemLookUpEdit1});
            this.mainRibbonControl.RibbonStyle = DevExpress.XtraBars.Ribbon.RibbonControlStyle.Office2013;
            this.mainRibbonControl.ShowApplicationButton = DevExpress.Utils.DefaultBoolean.False;
            this.mainRibbonControl.Size = new System.Drawing.Size(1073, 116);
            this.mainRibbonControl.ToolbarLocation = DevExpress.XtraBars.Ribbon.RibbonQuickAccessToolbarLocation.Hidden;
            // 
            // bbiSave
            // 
            this.bbiSave.Caption = "Snimi";
            this.bbiSave.Id = 2;
            this.bbiSave.ImageOptions.ImageUri.Uri = "Save";
            this.bbiSave.Name = "bbiSave";
            this.bbiSave.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiSave_ItemClick);
            // 
            // bbiSaveAndClose
            // 
            this.bbiSaveAndClose.Caption = "Save And Close";
            this.bbiSaveAndClose.Id = 3;
            this.bbiSaveAndClose.ImageOptions.ImageUri.Uri = "SaveAndClose";
            this.bbiSaveAndClose.Name = "bbiSaveAndClose";
            this.bbiSaveAndClose.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            // 
            // bbiSaveAndNew
            // 
            this.bbiSaveAndNew.Caption = "Save And New";
            this.bbiSaveAndNew.Id = 4;
            this.bbiSaveAndNew.ImageOptions.ImageUri.Uri = "SaveAndNew";
            this.bbiSaveAndNew.Name = "bbiSaveAndNew";
            this.bbiSaveAndNew.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            // 
            // bbiReset
            // 
            this.bbiReset.Caption = "Osvježi";
            this.bbiReset.Id = 5;
            this.bbiReset.ImageOptions.ImageUri.Uri = "Reset";
            this.bbiReset.Name = "bbiReset";
            // 
            // bbiDelete
            // 
            this.bbiDelete.Caption = "Obriši";
            this.bbiDelete.Id = 6;
            this.bbiDelete.ImageOptions.ImageUri.Uri = "Delete";
            this.bbiDelete.Name = "bbiDelete";
            this.bbiDelete.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            // 
            // bbiClose
            // 
            this.bbiClose.Caption = "Zatvori";
            this.bbiClose.Id = 7;
            this.bbiClose.ImageOptions.ImageUri.Uri = "Close";
            this.bbiClose.Name = "bbiClose";
            this.bbiClose.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            // 
            // barEditItem1
            // 
            this.barEditItem1.Caption = "barEditItem1";
            this.barEditItem1.Edit = this.repositoryItemLookUpEdit1;
            this.barEditItem1.Id = 10;
            this.barEditItem1.Name = "barEditItem1";
            // 
            // repositoryItemLookUpEdit1
            // 
            this.repositoryItemLookUpEdit1.AutoHeight = false;
            this.repositoryItemLookUpEdit1.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.repositoryItemLookUpEdit1.Name = "repositoryItemLookUpEdit1";
            // 
            // mainRibbonPage
            // 
            this.mainRibbonPage.Groups.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPageGroup[] {
            this.mainRibbonPageGroup});
            this.mainRibbonPage.MergeOrder = 0;
            this.mainRibbonPage.Name = "mainRibbonPage";
            this.mainRibbonPage.Text = "Kadrovska evidencija";
            // 
            // mainRibbonPageGroup
            // 
            this.mainRibbonPageGroup.AllowTextClipping = false;
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSave);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSaveAndClose);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSaveAndNew);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiReset);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiDelete);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiClose);
            this.mainRibbonPageGroup.Name = "mainRibbonPageGroup";
            this.mainRibbonPageGroup.ShowCaptionButton = false;
            this.mainRibbonPageGroup.Text = "Podaci";
            // 
            // xtraTabControl1
            // 
            this.xtraTabControl1.Location = new System.Drawing.Point(12, 332);
            this.xtraTabControl1.Name = "xtraTabControl1";
            this.xtraTabControl1.SelectedTabPage = this.xtraTabPage1;
            this.xtraTabControl1.Size = new System.Drawing.Size(1049, 358);
            this.xtraTabControl1.TabIndex = 10;
            this.xtraTabControl1.TabPages.AddRange(new DevExpress.XtraTab.XtraTabPage[] {
            this.xtraTabPage1,
            this.xtraTabPage2});
            // 
            // xtraTabPage1
            // 
            this.xtraTabPage1.Name = "xtraTabPage1";
            this.xtraTabPage1.Size = new System.Drawing.Size(1043, 330);
            this.xtraTabPage1.Text = "xtraTabPage1";
            // 
            // xtraTabPage2
            // 
            this.xtraTabPage2.Name = "xtraTabPage2";
            this.xtraTabPage2.Size = new System.Drawing.Size(1043, 330);
            this.xtraTabPage2.Text = "xtraTabPage2";
            // 
            // memoEdit1
            // 
            this.memoEdit1.Location = new System.Drawing.Point(280, 134);
            this.memoEdit1.MenuManager = this.mainRibbonControl;
            this.memoEdit1.Name = "memoEdit1";
            this.memoEdit1.Size = new System.Drawing.Size(769, 182);
            this.memoEdit1.StyleController = this.dataLayoutControl1;
            this.memoEdit1.TabIndex = 7;
            // 
            // pictureEdit1
            // 
            this.pictureEdit1.Cursor = System.Windows.Forms.Cursors.Default;
            this.pictureEdit1.Location = new System.Drawing.Point(12, 12);
            this.pictureEdit1.MenuManager = this.mainRibbonControl;
            this.pictureEdit1.Name = "pictureEdit1";
            contextButton1.Alignment = DevExpress.Utils.ContextItemAlignment.BottomFar;
            contextButton1.Caption = "Dodaj/promjeni fotografiju";
            contextButton1.Id = new System.Guid("8877d5fc-004a-4264-9174-58d9edcc153b");
            contextButton1.Name = "btnUcitajSliku";
            contextButton1.ToolTip = "Učitaj sliku";
            this.pictureEdit1.Properties.ContextButtons.Add(contextButton1);
            this.pictureEdit1.Properties.InitialImage = ((System.Drawing.Image)(resources.GetObject("pictureEdit1.Properties.InitialImage")));
            this.pictureEdit1.Properties.ShowCameraMenuItem = DevExpress.XtraEditors.Controls.CameraMenuItemVisibility.Auto;
            this.pictureEdit1.Properties.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Squeeze;
            this.pictureEdit1.Properties.ZoomAccelerationFactor = 1D;
            this.pictureEdit1.Size = new System.Drawing.Size(252, 316);
            this.pictureEdit1.StyleController = this.dataLayoutControl1;
            this.pictureEdit1.TabIndex = 4;
            this.pictureEdit1.ContextButtonClick += new DevExpress.Utils.ContextItemClickEventHandler(this.pictureEdit1_ContextButtonClick);
            // 
            // txtPrezime
            // 
            this.txtPrezime.EditValue = "";
            this.txtPrezime.Location = new System.Drawing.Point(364, 36);
            this.txtPrezime.MenuManager = this.mainRibbonControl;
            this.txtPrezime.Name = "txtPrezime";
            this.txtPrezime.Size = new System.Drawing.Size(303, 20);
            this.txtPrezime.StyleController = this.dataLayoutControl1;
            this.txtPrezime.TabIndex = 5;
            // 
            // txtIme
            // 
            this.txtIme.Location = new System.Drawing.Point(767, 36);
            this.txtIme.MenuManager = this.mainRibbonControl;
            this.txtIme.Name = "txtIme";
            this.txtIme.Size = new System.Drawing.Size(294, 20);
            this.txtIme.StyleController = this.dataLayoutControl1;
            this.txtIme.TabIndex = 6;
            // 
            // txtDjevPrezime
            // 
            this.txtDjevPrezime.Location = new System.Drawing.Point(364, 60);
            this.txtDjevPrezime.MenuManager = this.mainRibbonControl;
            this.txtDjevPrezime.Name = "txtDjevPrezime";
            this.txtDjevPrezime.Size = new System.Drawing.Size(303, 20);
            this.txtDjevPrezime.StyleController = this.dataLayoutControl1;
            this.txtDjevPrezime.TabIndex = 8;
            // 
            // txtImeOca
            // 
            this.txtImeOca.Location = new System.Drawing.Point(767, 60);
            this.txtImeOca.MenuManager = this.mainRibbonControl;
            this.txtImeOca.Name = "txtImeOca";
            this.txtImeOca.Size = new System.Drawing.Size(294, 20);
            this.txtImeOca.StyleController = this.dataLayoutControl1;
            this.txtImeOca.TabIndex = 9;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGeneratedGroup0});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Size = new System.Drawing.Size(1073, 702);
            this.layoutControlGroup1.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            this.autoGeneratedGroup0.AllowDrawBackground = false;
            this.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.GroupBordersVisible = false;
            this.autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForRoot});
            this.autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
            this.autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.Size = new System.Drawing.Size(1053, 682);
            // 
            // autoGroupForRoot
            // 
            this.autoGroupForRoot.CustomizationFormText = "Root";
            this.autoGroupForRoot.GroupBordersVisible = false;
            this.autoGroupForRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForPhoto});
            this.autoGroupForRoot.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForRoot.Name = "autoGroupForRoot";
            this.autoGroupForRoot.Size = new System.Drawing.Size(1053, 682);
            this.autoGroupForRoot.Text = "Root";
            // 
            // autoGroupForPhoto
            // 
            this.autoGroupForPhoto.CustomizationFormText = "Photo";
            this.autoGroupForPhoto.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForPhoto.GroupBordersVisible = false;
            this.autoGroupForPhoto.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem1,
            this.autoGroupForFirstAndLastName,
            this.layoutControlItem7});
            this.autoGroupForPhoto.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForPhoto.Name = "autoGroupForPhoto";
            this.autoGroupForPhoto.Size = new System.Drawing.Size(1053, 682);
            this.autoGroupForPhoto.Text = "Photo";
            // 
            // layoutControlItem1
            // 
            this.layoutControlItem1.Control = this.pictureEdit1;
            this.layoutControlItem1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new System.Drawing.Size(256, 320);
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            // 
            // autoGroupForFirstAndLastName
            // 
            this.autoGroupForFirstAndLastName.CustomizationFormText = "FirstAndLastName";
            this.autoGroupForFirstAndLastName.GroupBordersVisible = false;
            this.autoGroupForFirstAndLastName.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForTabs,
            this.layoutControlItem2,
            this.layoutControlItem3,
            this.layoutControlItem5,
            this.layoutControlItem6,
            this.layoutControlItem8,
            this.layoutControlItem9});
            this.autoGroupForFirstAndLastName.Location = new System.Drawing.Point(256, 0);
            this.autoGroupForFirstAndLastName.Name = "autoGroupForFirstAndLastName";
            this.autoGroupForFirstAndLastName.Size = new System.Drawing.Size(797, 320);
            this.autoGroupForFirstAndLastName.Text = "FirstAndLastName";
            // 
            // autoGroupForTabs
            // 
            this.autoGroupForTabs.CustomizationFormText = "Tabs";
            this.autoGroupForTabs.Location = new System.Drawing.Point(0, 72);
            this.autoGroupForTabs.Name = "autoGroupForTabs";
            this.autoGroupForTabs.SelectedTabPage = this.autoGroupForContact;
            this.autoGroupForTabs.SelectedTabPageIndex = 0;
            this.autoGroupForTabs.Size = new System.Drawing.Size(797, 248);
            this.autoGroupForTabs.TabPages.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForContact,
            this.autoGroupForJob,
            this.layoutControlGroup2});
            this.autoGroupForTabs.Text = "Tabs";
            // 
            // autoGroupForContact
            // 
            this.autoGroupForContact.CustomizationFormText = "Contact";
            this.autoGroupForContact.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForBDateAndGender,
            this.autoGroupForHomeAddressAndPhone});
            this.autoGroupForContact.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForContact.Name = "autoGroupForContact";
            this.autoGroupForContact.Size = new System.Drawing.Size(773, 202);
            this.autoGroupForContact.Text = "Contact";
            // 
            // autoGroupForBDateAndGender
            // 
            this.autoGroupForBDateAndGender.CustomizationFormText = "BDateAndGender";
            this.autoGroupForBDateAndGender.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForBDateAndGender.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForBDateAndGender.Name = "autoGroupForBDateAndGender";
            this.autoGroupForBDateAndGender.Size = new System.Drawing.Size(773, 67);
            this.autoGroupForBDateAndGender.Text = "BDateAndGender";
            // 
            // autoGroupForHomeAddressAndPhone
            // 
            this.autoGroupForHomeAddressAndPhone.CustomizationFormText = "HomeAddressAndPhone";
            this.autoGroupForHomeAddressAndPhone.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForHomeAddressAndPhone.Location = new System.Drawing.Point(0, 67);
            this.autoGroupForHomeAddressAndPhone.Name = "autoGroupForHomeAddressAndPhone";
            this.autoGroupForHomeAddressAndPhone.Size = new System.Drawing.Size(773, 135);
            this.autoGroupForHomeAddressAndPhone.Text = "HomeAddressAndPhone";
            // 
            // autoGroupForJob
            // 
            this.autoGroupForJob.CustomizationFormText = "Job";
            this.autoGroupForJob.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForHDateAndSalary,
            this.autoGroupForEmailAndSkype,
            this.autoGroupForGroupAndTitle});
            this.autoGroupForJob.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForJob.Name = "autoGroupForJob";
            this.autoGroupForJob.Size = new System.Drawing.Size(773, 202);
            this.autoGroupForJob.Text = "Job";
            // 
            // autoGroupForHDateAndSalary
            // 
            this.autoGroupForHDateAndSalary.CustomizationFormText = "HDateAndSalary";
            this.autoGroupForHDateAndSalary.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForHDateAndSalary.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForHDateAndSalary.Name = "autoGroupForHDateAndSalary";
            this.autoGroupForHDateAndSalary.Size = new System.Drawing.Size(773, 67);
            this.autoGroupForHDateAndSalary.Text = "HDateAndSalary";
            // 
            // autoGroupForEmailAndSkype
            // 
            this.autoGroupForEmailAndSkype.CustomizationFormText = "EmailAndSkype";
            this.autoGroupForEmailAndSkype.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForEmailAndSkype.Location = new System.Drawing.Point(0, 67);
            this.autoGroupForEmailAndSkype.Name = "autoGroupForEmailAndSkype";
            this.autoGroupForEmailAndSkype.Size = new System.Drawing.Size(773, 68);
            this.autoGroupForEmailAndSkype.Text = "EmailAndSkype";
            // 
            // autoGroupForGroupAndTitle
            // 
            this.autoGroupForGroupAndTitle.CustomizationFormText = "GroupAndTitle";
            this.autoGroupForGroupAndTitle.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForGroupAndTitle.Location = new System.Drawing.Point(0, 135);
            this.autoGroupForGroupAndTitle.Name = "autoGroupForGroupAndTitle";
            this.autoGroupForGroupAndTitle.Size = new System.Drawing.Size(773, 67);
            this.autoGroupForGroupAndTitle.Text = "GroupAndTitle";
            // 
            // layoutControlGroup2
            // 
            this.layoutControlGroup2.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem4});
            this.layoutControlGroup2.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup2.Name = "layoutControlGroup2";
            this.layoutControlGroup2.Size = new System.Drawing.Size(773, 202);
            this.layoutControlGroup2.Text = "Napomena";
            // 
            // layoutControlItem4
            // 
            this.layoutControlItem4.Control = this.memoEdit1;
            this.layoutControlItem4.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem4.Name = "layoutControlItem4";
            this.layoutControlItem4.Size = new System.Drawing.Size(773, 202);
            this.layoutControlItem4.TextLocation = DevExpress.Utils.Locations.Top;
            this.layoutControlItem4.TextSize = new System.Drawing.Size(93, 13);
            // 
            // layoutControlItem2
            // 
            this.layoutControlItem2.Control = this.txtPrezime;
            this.layoutControlItem2.Location = new System.Drawing.Point(0, 24);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new System.Drawing.Size(403, 24);
            this.layoutControlItem2.Text = "Prezime";
            this.layoutControlItem2.TextSize = new System.Drawing.Size(93, 13);
            // 
            // layoutControlItem3
            // 
            this.layoutControlItem3.Control = this.txtIme;
            this.layoutControlItem3.Location = new System.Drawing.Point(403, 24);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new System.Drawing.Size(394, 24);
            this.layoutControlItem3.Text = "Ime";
            this.layoutControlItem3.TextSize = new System.Drawing.Size(93, 13);
            // 
            // layoutControlItem5
            // 
            this.layoutControlItem5.Control = this.txtDjevPrezime;
            this.layoutControlItem5.Location = new System.Drawing.Point(0, 48);
            this.layoutControlItem5.Name = "layoutControlItem5";
            this.layoutControlItem5.Size = new System.Drawing.Size(403, 24);
            this.layoutControlItem5.Text = "Djevojačko prezime";
            this.layoutControlItem5.TextSize = new System.Drawing.Size(93, 13);
            // 
            // layoutControlItem6
            // 
            this.layoutControlItem6.Control = this.txtImeOca;
            this.layoutControlItem6.Location = new System.Drawing.Point(403, 48);
            this.layoutControlItem6.Name = "layoutControlItem6";
            this.layoutControlItem6.Size = new System.Drawing.Size(394, 24);
            this.layoutControlItem6.Text = "Ime oca";
            this.layoutControlItem6.TextSize = new System.Drawing.Size(93, 13);
            // 
            // layoutControlItem8
            // 
            this.layoutControlItem8.Control = this.txtJMBG;
            this.layoutControlItem8.Location = new System.Drawing.Point(175, 0);
            this.layoutControlItem8.Name = "layoutControlItem8";
            this.layoutControlItem8.Size = new System.Drawing.Size(622, 24);
            this.layoutControlItem8.Text = "JMBG";
            this.layoutControlItem8.TextSize = new System.Drawing.Size(93, 13);
            // 
            // layoutControlItem7
            // 
            this.layoutControlItem7.Control = this.xtraTabControl1;
            this.layoutControlItem7.Location = new System.Drawing.Point(0, 320);
            this.layoutControlItem7.Name = "layoutControlItem7";
            this.layoutControlItem7.Size = new System.Drawing.Size(1053, 362);
            this.layoutControlItem7.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem7.TextVisible = false;
            // 
            // txtID
            // 
            this.txtID.Location = new System.Drawing.Point(364, 12);
            this.txtID.MenuManager = this.mainRibbonControl;
            this.txtID.Name = "txtID";
            this.txtID.Properties.ReadOnly = true;
            this.txtID.Size = new System.Drawing.Size(75, 20);
            this.txtID.StyleController = this.dataLayoutControl1;
            this.txtID.TabIndex = 12;
            // 
            // layoutControlItem9
            // 
            this.layoutControlItem9.Control = this.txtID;
            this.layoutControlItem9.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem9.Name = "layoutControlItem9";
            this.layoutControlItem9.Size = new System.Drawing.Size(175, 24);
            this.layoutControlItem9.Text = "Šifra";
            this.layoutControlItem9.TextSize = new System.Drawing.Size(93, 13);
            // 
            // ucRadnik
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.Controls.Add(this.dataLayoutControl1);
            this.Controls.Add(this.mainRibbonControl);
            this.Name = "ucRadnik";
            this.Size = new System.Drawing.Size(1073, 818);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txtJMBG.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.mainRibbonControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemLookUpEdit1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.xtraTabControl1)).EndInit();
            this.xtraTabControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.memoEdit1.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureEdit1.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtPrezime.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtIme.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtDjevPrezime.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtImeOca.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForRoot)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForPhoto)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForFirstAndLastName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForTabs)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForContact)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForBDateAndGender)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForHomeAddressAndPhone)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForJob)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForHDateAndSalary)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForEmailAndSkype)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForGroupAndTitle)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtID.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraBars.Ribbon.RibbonControl mainRibbonControl;
        private DevExpress.XtraBars.Ribbon.RibbonPage mainRibbonPage;
        private DevExpress.XtraBars.Ribbon.RibbonPageGroup mainRibbonPageGroup;
        private DevExpress.XtraBars.BarButtonItem bbiSave;
        private DevExpress.XtraBars.BarButtonItem bbiSaveAndClose;
        private DevExpress.XtraBars.BarButtonItem bbiSaveAndNew;
        private DevExpress.XtraBars.BarButtonItem bbiReset;
        private DevExpress.XtraBars.BarButtonItem bbiDelete;
        private DevExpress.XtraBars.BarButtonItem bbiClose;
        private DevExpress.XtraBars.BarEditItem barEditItem1;
        private DevExpress.XtraEditors.Repository.RepositoryItemLookUpEdit repositoryItemLookUpEdit1;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForRoot;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForPhoto;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForFirstAndLastName;
        private DevExpress.XtraLayout.TabbedControlGroup autoGroupForTabs;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForContact;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForBDateAndGender;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForHomeAddressAndPhone;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForJob;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForHDateAndSalary;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForEmailAndSkype;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForGroupAndTitle;
        private DevExpress.XtraTab.XtraTabControl xtraTabControl1;
        private DevExpress.XtraTab.XtraTabPage xtraTabPage1;
        private DevExpress.XtraTab.XtraTabPage xtraTabPage2;
        private DevExpress.XtraEditors.MemoEdit memoEdit1;
        private DevExpress.XtraEditors.PictureEdit pictureEdit1;
        private DevExpress.XtraEditors.TextEdit txtPrezime;
        private DevExpress.XtraEditors.TextEdit txtIme;
        private DevExpress.XtraEditors.TextEdit txtDjevPrezime;
        private DevExpress.XtraEditors.TextEdit txtImeOca;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem4;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem3;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem5;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem6;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem7;
        private DevExpress.XtraEditors.TextEdit txtJMBG;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem8;
        private DevExpress.XtraEditors.TextEdit txtID;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem9;
    }
}
