// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `data source=DESKTOP-L1OSIDV\SQLEXPRESS;initial catalog=Kadrovska;Trusted_Connection=false;User ID=sa; Password=test; Connection Timeout = 0;`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `data source=DESKTOP-L1OSIDV\SQLEXPRESS;initial catalog=Kadrovska;Trusted_Connection=false;User ID=sa; Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace Kadrovska_sluzba.DB.Models
{
    /// <summary>
    /// A class which represents the PorodicnoStanje table.
    /// </summary>
	[Table("PorodicnoStanje")]
	public partial class PorodicnoStanje
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
	}

    /// <summary>
    /// A class which represents the Mjesto table.
    /// </summary>
	[Table("Mjesto")]
	public partial class Mjesto
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int? OpstinaID { get; set; }
		public virtual int PostBr { get; set; }
		public virtual string Naziv { get; set; }
	}

    /// <summary>
    /// A class which represents the PoslovnaJedinica table.
    /// </summary>
	[Table("PoslovnaJedinica")]
	public partial class PoslovnaJedinica
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string PuniNaziv { get; set; }
		public virtual int? Mjesto { get; set; }
		public virtual string Adresa { get; set; }
		public virtual string Telefon { get; set; }
		public virtual string Fax { get; set; }
		public virtual string Mobilni { get; set; }
		public virtual string Maticni { get; set; }
		public virtual string PIB { get; set; }
		public virtual string JIB { get; set; }
		public virtual string Ziro { get; set; }
		public virtual string Web { get; set; }
		public virtual string Mail { get; set; }
	}

    /// <summary>
    /// A class which represents the TipRadnogOdnosa table.
    /// </summary>
	[Table("TipRadnogOdnosa")]
	public partial class TipRadnogOdnosa
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string Opis { get; set; }
		public virtual int? Bitovi { get; set; }
	}

    /// <summary>
    /// A class which represents the Firma table.
    /// </summary>
	[Table("Firma")]
	public partial class Firma
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string PuniNaziv { get; set; }
		public virtual int? Mjesto { get; set; }
		public virtual string Adresa { get; set; }
		public virtual string Telefon { get; set; }
		public virtual string Fax { get; set; }
		public virtual string Mobilni { get; set; }
		public virtual string Maticni { get; set; }
		public virtual string PIB { get; set; }
		public virtual string JIB { get; set; }
		public virtual string Ziro { get; set; }
		public virtual string Web { get; set; }
		public virtual string Mail { get; set; }
	}

    /// <summary>
    /// A class which represents the RadnoMjesto table.
    /// </summary>
	[Table("RadnoMjesto")]
	public partial class RadnoMjesto
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string Opis { get; set; }
	}

    /// <summary>
    /// A class which represents the StrucnaSprema table.
    /// </summary>
	[Table("StrucnaSprema")]
	public partial class StrucnaSprema
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string Opis { get; set; }
	}

    /// <summary>
    /// A class which represents the RadnikDjeca table.
    /// </summary>
	[Table("RadnikDjeca")]
	public partial class RadnikDjeca
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int RadID { get; set; }
		public virtual string Ime { get; set; }
		public virtual DateTime? DatumRodj { get; set; }
		public virtual string JMBG { get; set; }
		public virtual int Bitovi { get; set; }
		public virtual string Napomena { get; set; }
	}

    /// <summary>
    /// A class which represents the NacinPrestankaRO table.
    /// </summary>
	[Table("NacinPrestankaRO")]
	public partial class NacinPrestankaRO
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string Opis { get; set; }
	}

    /// <summary>
    /// A class which represents the Opstina table.
    /// </summary>
	[Table("Opstina")]
	public partial class Opstina
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Sifra { get; set; }
		public virtual string Naziv { get; set; }
	}

    /// <summary>
    /// A class which represents the RadnikStaz view.
    /// </summary>
	[Table("RadnikStaz")]
	public partial class RadnikStaz
	{
		public virtual int RadID { get; set; }
		public virtual int Godina { get; set; }
		public virtual int Mjeseci { get; set; }
		public virtual int Dana { get; set; }
		public virtual int StazGPrethodni { get; set; }
		public virtual int StazMjPrethodni { get; set; }
		public virtual int? StazDanaPrethodni { get; set; }
		public virtual int? G { get; set; }
		public virtual int? M { get; set; }
		public virtual int? D { get; set; }
	}

    /// <summary>
    /// A class which represents the Nacionalnost table.
    /// </summary>
	[Table("Nacionalnost")]
	public partial class Nacionalnost
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
	}

    /// <summary>
    /// A class which represents the RadnikGO table.
    /// </summary>
	[Table("RadnikGO")]
	public partial class RadnikGO
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int RadID { get; set; }
		public virtual DateTime? DatumOd { get; set; }
		public virtual DateTime? DatumDo { get; set; }
		public virtual int Zaduzio { get; set; }
		public virtual int Razduzio { get; set; }
		public virtual string Napomena { get; set; }
	}

    /// <summary>
    /// A class which represents the Drzavljanstvo table.
    /// </summary>
	[Table("Drzavljanstvo")]
	public partial class Drzavljanstvo
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
	}

}
