// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `data source=DESKTOP-L1OSIDV\SQLEXPRESS;initial catalog=Kadrovska;Trusted_Connection=false;User ID=sa; Password=test; Connection Timeout = 0;`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `data source=DESKTOP-L1OSIDV\SQLEXPRESS;initial catalog=Kadrovska;Trusted_Connection=false;User ID=sa; Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace Kadrovska_sluzba.DB.Models
{
    /// <summary>
    /// A class which represents the Firma table.
    /// </summary>
	[Table("Firma")]
	public partial class Firma
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string PuniNaziv { get; set; }
		public virtual string PostBroj { get; set; }
		public virtual string Adresa { get; set; }
		public virtual string Telefon { get; set; }
		public virtual string Fax { get; set; }
		public virtual string Mobilni { get; set; }
		public virtual string Maticni { get; set; }
		public virtual string PIB { get; set; }
		public virtual string JIB { get; set; }
		public virtual string Ziro { get; set; }
		public virtual string Web { get; set; }
		public virtual string Mail { get; set; }
		//public virtual Mjesto Mjesto { get; set; }
	}

    /// <summary>
    /// A class which represents the PoslovnaJedinica table.
    /// </summary>
	[Table("PoslovnaJedinica")]
	public partial class PoslovnaJedinica
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string PuniNaziv { get; set; }
		public virtual string PostBroj { get; set; }
		public virtual string Adresa { get; set; }
		public virtual string Telefon { get; set; }
		public virtual string Fax { get; set; }
		public virtual string Mobilni { get; set; }
		public virtual string Maticni { get; set; }
		public virtual string PIB { get; set; }
		public virtual string JIB { get; set; }
		public virtual string Ziro { get; set; }
		public virtual string Web { get; set; }
		public virtual string Mail { get; set; }
		//public virtual Mjesto Mjesto { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

    /// <summary>
    /// A class which represents the PorodicnoStanje table.
    /// </summary>
	[Table("PorodicnoStanje")]
	public partial class PorodicnoStanje
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

    /// <summary>
    /// A class which represents the TipRadnogOdnosa table.
    /// </summary>
	[Table("TipRadnogOdnosa")]
	public partial class TipRadnogOdnosa
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string Opis { get; set; }
		public virtual int? Bitovi { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

    /// <summary>
    /// A class which represents the RadnoMjesto table.
    /// </summary>
	[Table("RadnoMjesto")]
	public partial class RadnoMjesto
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string Opis { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

    /// <summary>
    /// A class which represents the StrucnaSprema table.
    /// </summary>
	[Table("StrucnaSprema")]
	public partial class StrucnaSprema
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string Opis { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

    /// <summary>
    /// A class which represents the RadnikDjeca table.
    /// </summary>
	[Table("RadnikDjeca")]
	public partial class RadnikDjeca
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int RadID { get; set; }
		public virtual string Ime { get; set; }
		public virtual DateTime? DatumRodj { get; set; }
		public virtual string JMBG { get; set; }
		public virtual int Bitovi { get; set; }
		public virtual string Napomena { get; set; }
		//public virtual Radnik Radnik { get; set; }
	}

 //   /// <summary>
 //   /// A class which represents the sysdiagrams table.
 //   /// </summary>
	//[Table("sysdiagrams")]
	//public partial class sysdiagram
	//{
	//	public virtual string name { get; set; }
	//	public virtual int principal_id { get; set; }
	//	[Key]
	//	public virtual int diagram_id { get; set; }
	//	public virtual int? version { get; set; }
	//	public virtual byte[] definition { get; set; }
	//}

    /// <summary>
    /// A class which represents the NacinPrestankaRO table.
    /// </summary>
	[Table("NacinPrestankaRO")]
	public partial class NacinPrestankaRO
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string Opis { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

    /// <summary>
    /// A class which represents the Opstina table.
    /// </summary>
	[Table("Opstina")]
	public partial class Opstina
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Sifra { get; set; }
		public virtual string Naziv { get; set; }
		//public virtual IEnumerable<Mjesto> Mjesto { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

    /// <summary>
    /// A class which represents the Radnik table.
    /// </summary>
	[Table("Radnik")]
	public partial class Radnik
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string JMBG { get; set; }
		public virtual string Prezime { get; set; }
		public virtual string DjevPrezime { get; set; }
		public virtual string Ime { get; set; }
		public virtual string ImeOca { get; set; }
		public virtual int Bitovi { get; set; }
		public virtual string Titula { get; set; }
		public virtual string Funkcija { get; set; }
		public virtual int? MjestoRodjenja { get; set; }
		public virtual DateTime? DatumRodjenja { get; set; }
		public virtual int? DrzavljanstvoID { get; set; }
		public virtual int? NacionalnostID { get; set; }
		public virtual int? PorodicnoStanjeID { get; set; }
		public virtual int? MjestoStan { get; set; }
		public virtual string AdresaStan { get; set; }
		public virtual string TelefonStan { get; set; }
		public virtual string TelefonMob { get; set; }
		public virtual string TelefonPosao { get; set; }
		public virtual string Zanimanje { get; set; }
		public virtual int? StrucnaSpremaID { get; set; }
		public virtual string ZavrsenaSkola { get; set; }
		public virtual int? RadnoMjestoID { get; set; }
		public virtual string BrLK { get; set; }
		public virtual string BrRadneKnj { get; set; }
		public virtual int? OpstinaIzdavanjaRK { get; set; }
		public virtual string LicniBrOsiguranja { get; set; }
		public virtual DateTime? DatumPrvogZapos { get; set; }
		public virtual int? PrethodniStazMj { get; set; }
		public virtual int? PrethodniStazDan { get; set; }
		public virtual int? PrethodniStazUFirmiMj { get; set; }
		public virtual int? PrethodniStazUFirmiDan { get; set; }
		public virtual DateTime? DatumZapos { get; set; }
		public virtual int? TipRadnogOdnosaID { get; set; }
		public virtual int? NacinPrestankaRoID { get; set; }
		public virtual DateTime? DatumPrestankaRO { get; set; }
		public virtual string Napomena { get; set; }
		public virtual string FindStr { get; set; }
		public virtual string Lozinka { get; set; }
		public virtual byte[] Slika { get; set; }
		public virtual string Naziv { get; set; }
		public virtual string eMail { get; set; }
		public virtual int? PoslovnaJedinicaID { get; set; }
        public virtual string Pol { get; set; }

        //public virtual Mjesto Mjesto { get; set; }
        //public virtual Opstina Opstina { get; set; }
        //public virtual Drzavljanstvo Drzavljanstvo { get; set; }
        //public virtual Nacionalnost Nacionalnost { get; set; }
        //public virtual PorodicnoStanje PorodicnoStanje { get; set; }
        //public virtual Mjesto Mjesto { get; set; }
        //public virtual Opstina Opstina { get; set; }
        //public virtual StrucnaSprema StrucnaSprema { get; set; }
        //public virtual RadnoMjesto RadnoMjesto { get; set; }
        //public virtual Opstina Opstina { get; set; }
        //public virtual TipRadnogOdnosa TipRadnogOdnosa { get; set; }
        //public virtual NacinPrestankaRO NacinPrestankaRO { get; set; }
        //public virtual PoslovnaJedinica PoslovnaJedinica { get; set; }
        //public virtual IEnumerable<RadnikDjeca> RadnikDjeca { get; set; }
    }

    /// <summary>
    /// A class which represents the Mjesto table.
    /// </summary>
	[Table("Mjesto")]
	public partial class Mjesto
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual int? OpstinaID { get; set; }
		public virtual string PostBr { get; set; }
		public virtual string Naziv { get; set; }
		//public virtual Opstina Opstina { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
		//public virtual IEnumerable<Firma> Firma { get; set; }
		//public virtual IEnumerable<PoslovnaJedinica> PoslovnaJedinica { get; set; }
	}

    /// <summary>
    /// A class which represents the Nacionalnost table.
    /// </summary>
	[Table("Nacionalnost")]
	public partial class Nacionalnost
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

    /// <summary>
    /// A class which represents the Drzavljanstvo table.
    /// </summary>
	[Table("Drzavljanstvo")]
	public partial class Drzavljanstvo
	{
		[Key]
		public virtual int ID { get; set; }
		public virtual string Naziv { get; set; }
		//public virtual IEnumerable<Radnik> Radnik { get; set; }
	}

}
